# docker build -t llamafile-server-single -f Dockerfile.single .
FROM debian:bullseye-slim
WORKDIR /app
COPY execute/llava-v1.5-7b-q4-server.llamafile llamafile-server
RUN chmod +x ./llamafile-server
RUN addgroup --gid 1000 user
RUN adduser --uid 1000 --gid 1000 --disabled-password --gecos "" user
# Switch to user.
USER user
EXPOSE 8080
# Set entrypoint.
ENTRYPOINT ["/bin/sh", "/app/llamafile-server", "--host", "0.0.0.0"]