services:
  ollamaweb:
    image: ghcr.io/open-webui/open-webui:ollama
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
      - ./open-webui:/app/backend/data
    ports:
      - 9901:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]