services:
  ollama:
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./data_ollama:/root/.ollama
    deploy:
      resources:
        limits:
          # cpus: '18'
          memory: 32G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    restart: unless-stopped
    ports:
      - 9901:8080
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - USE_CUDA_DOCKER=true
      - WHISPER_MODEL=medium
      - TZ=Asia/Bangkok
    volumes:
      - ./data_open-webui:/app/backend/data
    deploy:
      resources:
        limits:
          # cpus: '18'
          memory: 32G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
