# Docker use this dashboard https://grafana.com/grafana/dashboards/8321
# sample config from https://grafana.com/grafana/dashboards/893

# section 1
global: 
  scrape_interval: 15s
  evaluation_interval: 15s
  # external_labels:
  #   monitor: 'node-monitor'  
  
# section 2  
scrape_configs: 
  - job_name: mqtt-exporter
    static_configs:
      - targets: ["mqtt-exporter:9000"]
    # metric_relabel_configs:
    #   - source_labels: [sensor]
    #     regex: 'zigbee2mqtt_(.*)'
    #     replacement: '$1'
    #     target_label: sensor

  # - job_name: prometheus
  #   scrape_interval: 10s 
  #   static_configs: 
  #     - targets: ["127.0.0.1:9090"]
      
  # - job_name: node-exporter
  #   scrape_interval: 10s 
  #   static_configs:
  #     - targets: ["prometheus-node-exporter:9100"]

  # - job_name: 'cadvisor'
  #   scrape_interval: 10s 
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #       labels:
  #         group: 'cadvisor'
